{
  "hash": "8949288cda761bfd3774b4b1e43e54d2",
  "result": {
    "engine": "knitr",
    "markdown": "# Visualization 1\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualization 1\n\n# Load in packages\nif (!require(\"pacman\")) \n  install.packages(\"pacman\")\n\npacman::p_load(tidyverse,\n               ggridges,\n               here,\n               RColorBrewer,\n               DescTools,\n               grid,\n               caTools,\n               pROC)\n\n\n#### Load in Data\nolympics <- read_csv(here(\"data\", \"athlete_events.csv\"))\n\n#### Data Prep\n\n# create decade column, years are rounded down for decade column (EX: Year=1896,Decade=1890)\nolympics$Decade <- floor(olympics$Year / 10) * 10\n\n# create height in inches column\nolympics$Height_Inches <- round(olympics$Height / 2.54)\n\n# create new df containing only basketball data\nbasketball <- subset(olympics, Sport == 'Basketball')\n\n# create height in feet column\nbasketball$Height_Ft <- floor(basketball$Height_Inches / 12)\n\n# create remainder of inches column\nbasketball$Height_Inches_Rem <- round(basketball$Height_Inches %% 12)\n\n# filter even further for only mens basketball data\nmens_basketball <- subset(basketball, Event %in% c(\"Basketball Men's Basketball\"))\n\n# convert decade column to factor for plotting\nmens_basketball$Decade = as.factor(mens_basketball$Decade)\n\n# find mode for 1930 and 2010\nbasketball_summary_stats_by_decade = mens_basketball |>\n  group_by(Decade) |>\n  summarize(mode = Mode(Height_Inches, na.rm = TRUE)) |>\n  ungroup()\n\nmens_basketball|>\n  ggplot(aes(x = Height_Inches, y = Decade, fill = Decade)) +\n  geom_density_ridges() +\n  scale_fill_brewer(palette = \"Oranges\") +\n  scale_x_continuous(breaks = seq(60, 90, by = 5)) +\n  labs(x = \"Height (inches)\",\n       y = NULL,\n       title = \"The Increase of Olympic Men's Basketball Player Heights\",\n       subtitle = \"from the 1930's to the 2010's\") +\n  geom_segment(aes(x = 80.65, y = 10.45, xend = 88, yend = 4.5), linewidth = 0.3) +\n  geom_segment(aes(x = 72.2, y = 2.7, xend = 88, yend = 4.5), linewidth = 0.3) +\n  geom_text(aes(x = 81.3, y = 10.8, label = \"6'8\\\"\"), size = 3) +\n  geom_text(aes(x = 72.7, y = 3.05, label = \"6'0\\\"\"), size = 3) +\n  annotate(\"point\", x = 80.65, y = 10.45, fill = \"red\", size = 3, shape = 21, stroke = 0.5) +\n  annotate(\"point\", x = 72.2, y = 2.7, fill = \"red\", size = 3, shape = 21, stroke = 0.5) +\n  geom_label(aes(x = 88, y = 4.5, label = \"The most common\\nplayer height has\\nincreased by 8 inches\\nsince the 1930's\"),\n             color = \"black\", fill = \"white\", size = 3, fontface = \"bold\") +\n  theme(legend.position = \"none\",\n        panel.background = element_rect(fill = \"white\"),\n        plot.title = element_text(face = \"bold\"),\n        axis.ticks.x = element_blank(),\n        axis.ticks.y = element_blank()) +\n  coord_cartesian(clip = \"off\")\n```\n\n::: {.cell-output-display}\n![](Q1_code_files/figure-html/Visualization 1-1.png){width=672}\n:::\n:::\n\n\n\n\n\n## Viz 1 References\n\n<https://r-coder.com/subset-r/>\n\n<https://stackoverflow.com/questions/35352914/floor-a-year-to-the-decade-in-r>\n\n# Visualization 2\n\nLogistic Regression Model\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add binary medal column: 1 = medal, 2 = no medal\nmens_basketball = mens_basketball |>\n  mutate(medal_bi = case_when(\n    Medal == \"Bronze\" ~ 1,\n    Medal == \"Silver\" ~ 1,\n    Medal == \"Gold\" ~ 1,\n    is.na(Medal) ~ 0\n  ))\n\n# Create 2 column df of height and medal_bi and remove NA's\nlogit_df = as.data.frame(cbind(mens_basketball$Height_Inches,\n                               mens_basketball$medal_bi))\ncolnames(logit_df) = c(\"height\",\n                       \"medal\")\nlogit_df = logit_df |>\n  drop_na(height)\n\n# Split into training and testing\nset.seed(123)\nsplit = sample.split(logit_df$medal, SplitRatio = 0.7)\ntrain_data = subset(logit_df, split == TRUE)\ntest_data = subset(logit_df, split == FALSE)\n\n# Fit the model\nmedal_logit = glm(medal ~ height, data = train_data, family = binomial)\nsummary(medal_logit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = medal ~ height, family = binomial, data = train_data)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -7.68948    1.06248  -7.237 4.58e-13 ***\nheight       0.08477    0.01370   6.189 6.05e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2029.4  on 1840  degrees of freedom\nResidual deviance: 1990.1  on 1839  degrees of freedom\nAIC: 1994.1\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test the model\ntest_data$pred_prob = predict(medal_logit, newdata = test_data, type = \"response\")\n\nroc_curve = roc(test_data$medal, test_data$pred_prob)\nplot(roc_curve)\n```\n\n::: {.cell-output-display}\n![](Q1_code_files/figure-html/Logistic Regression Viz 2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nauc(roc_curve)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.5973\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot the probabilities\nheight_seq = as.data.frame(seq(min(logit_df$height) - 20, max(logit_df$height) + 20, length.out = 100))\ncolnames(height_seq) = \"height\"\npred_prob2 = predict(medal_logit, newdata = height_seq, type = \"response\")\n\nplot_data = as.data.frame(cbind(height_seq,\n                                pred_prob2))\n\nplot_data |>\n  ggplot(aes(x = height, y = pred_prob2)) +\n  geom_line(size = 1) +\n  geom_jitter(data = test_data, aes(x = height, y = pred_prob, color = as.factor(medal)),\n              width = 0, height = 0.1, alpha = 0.6) + \n  scale_color_manual(\n    values = c(\"1\" = \"darkorange\", \"0\" = \"steelblue\"),\n    labels = c(\"Non-Medal Winner\", \"Medal Winner\"),\n    name = \"Medal Status\"\n  ) +\n  labs(\n    title = \"Probability of Winning an Olympic Medal by Height\",\n    subtitle = \"Logistic Regression Model\",\n    x = \"Height (in)\",\n    y = \"Predicted Probability\"\n  ) + \n  scale_y_continuous(\n    labels = scales::percent_format(),\n    breaks = seq(0, 1, 0.20)\n  ) +\n  theme_minimal() + \n  theme(\n    panel.grid = element_blank(),\n    plot.title = element_text(hjust = 0.5, size = 14, face = \"bold\"),\n    plot.subtitle = element_text(hjust = 0.5, size = 12),\n    axis.title = element_text(size = 12),\n    legend.position = \"right\",\n    legend.text = element_text(size = 10),\n    legend.title = element_text(size = 11, face = \"bold\"),\n    legend.background = element_rect(color = \"black\"),\n    aspect.ratio = 1/2\n  )\n```\n\n::: {.cell-output-display}\n![](Q1_code_files/figure-html/Logistic Regression Viz 2-2.png){width=672}\n:::\n:::\n\n\n\n\n\np-value = 6.05e-10 -\\> very statistically significant\n\nAUC = 0.5973 -\\> just slightly better than random guessing\n\n\\^Together these values mean that height and medal are strongly correlated, but the model is not good at predicting based on height alone.\n\nHeight Coef = 0.08477\n\nOdds Ratio = e\\^0.08477 = 1.0885\n\nFor every one inch increase in height, the odds of winning a medal increase by 8.85%\n\nConclusion: Height almost definitely plays a role in earning a medal in Olympic basketball, but there are many other important factors needed to accurately predict if a player will win a medal such as skills, team context, or other physical attributes.\n\n## Viz 2 References\n\n<https://www.rpubs.com/fangya/logr>\n\n<https://quarto.org/docs/dashboards/> (dashboard ref)\n\n<https://plotly.com/r/>\n",
    "supporting": [
      "Q1_code_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}